# This is a basic workflow
name: CI

# Triggers the workflow on all pushes or pull requests on any branch
on:
  push:
    branches: 
      - 'test'
  pull_request:
    branches: 
      - 'test'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # Re-added windows-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Run install dependencies (works for all OSes)
      - name: Install dependencies
        run: npm run install:ci

      # Build extension
      - name: Run build
        run: npm run package

      # Generate .vsix package for the extension (only for Linux and Windows)
      - name: Generate .vsix package
        if: runner.os == 'Linux' || runner.os == 'Windows'
        run: |
          npm install -g @vscode/vsce
          vsce package

      # Upload VSIX artifact (only for Linux and Windows)
      - name: Upload VSIX artifact
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: vscode-granite-vsix-${{ runner.os }}-${{ github.run_id }}  # Unique name with OS and run ID
          path: "./vscode-granite-*.vsix"

      ## Run tests
      - name: Run Tests
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            xvfb-run npm test
          elif [ "${{ runner.os }}" == "Windows" ]; then
            npm test
          else
            npm test

      # Update latest release (only on Linux and for main branch)
      - name: Update latest release
        if: (runner.os == 'Linux' || runner.os == 'Windows') && github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.vsix
