# This is a basic workflow for CI across multiple operating systems
name: CI

# Triggers the workflow on all pushes or pull requests on the 'test' branch
on:
  push:
    branches: 
      - 'test'
  pull_request:
    branches: 
      - 'test'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}  # This allows the job to run on each OS defined in the matrix

    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci  # Use npm ci for a clean install in CI environments

      # Build extension
      - name: Run build
        run: npm run package

      # Generate .vsix package for the extension
      - name: Generate .vsix package
        run: |
          npm install -g @vscode/vsce --no-fund --no-optional
          vsce package

      # Upload VSIX artifact
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-granite-vsix-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}  # Unique name with OS and run ID
          path: "./vscode-granite-*.vsix"

      # Run tests
      - name: Run Tests
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
             xvfb-run npm test
          else
             npm test
          fi

      # Update latest release (only for the main branch)
      - name: Update latest release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.vsix
